name: CI (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Cancela ejecuciones previas de la misma rama/PR
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable + fmt + clippy)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # Cache inteligente para Rust (registro, git deps y target/)
      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          # ajusta si tu workspace se llama distinto o si tienes varias crates
          workspaces: |
            . -> target

      - name: Show toolchain
        run: |
          rustc -V
          cargo -V

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features --locked --verbose

      - name: Build (release)
        run: cargo build --release --locked --verbose
